import Foundation
import UIKit

extension PushInboxStore {
    /// True for text written by a PERSON rather than by this app, which must not be persisted to
    /// disk on a child's device.
    ///
    /// Provenance is a property of the CALLER, not of the event name. This used to be inferred from
    /// an allowlist of three stems (`chat`/`message`/`sms`) tested against the event, which returned
    /// `false` — keep the body — for any unrecognised or EMPTY event. A chat push whose event the
    /// backend spelled differently, or omitted, therefore wrote the parent's message text to disk
    /// verbatim, defeating the guard it is.
    ///
    /// `remoteOrigin` is now passed explicitly and defaults to the safe answer: anything arriving
    /// from the backend is treated as potentially human-authored, while the app's OWN device-control
    /// notices (which it composes itself, from localized templates) keep their text.
    static func carriesPrivateContent(event: String, remoteOrigin: Bool = true) -> Bool {
        guard remoteOrigin else { return false }
        // Machine-authored remote commands carry no human text at all. They are already dropped
        // before reaching the inbox for having neither title nor body; this keeps the rule honest
        // for any that do arrive with a label.
        let tokens = Set(event.lowercased().split { !$0.isLetter && !$0.isNumber })
        let machineAuthored: Set<Substring> = ["lock", "stream", "status", "sync", "refresh", "ping"]
        if !tokens.isEmpty, tokens.contains(where: { machineAuthored.contains($0) }) { return false }
        return true
    }

    func append(
        title: String,
        body: String,
        event: String,
        dsn: String?,
        isRead: Bool,
        /// False for entries this app composes itself (device-control notices), whose body is a
        /// localized template rather than anything a person typed.
        remoteOrigin: Bool = true,
        receivedAt: Date = Date()
    ) {
        var items = storedItems()

        let normalizedTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
        let normalizedBody = body.trimmingCharacters(in: .whitespacesAndNewlines)
        let normalizedEvent = event.trimmingCharacters(in: .whitespacesAndNewlines)
        let normalizedDSN = dsn?.trimmedNonEmpty
        let now = receivedAt
        let fingerprint = Self.makeFingerprint(
            title: normalizedTitle,
            body: normalizedBody,
            event: normalizedEvent,
            dsn: normalizedDSN
        )

        if let duplicateIndex = items.firstIndex(where: { existing in
            existing.fingerprint == fingerprint &&
            abs(now.timeIntervalSince(existing.receivedAt)) < duplicateWindow
        }) {
            if items[duplicateIndex].isRead == false, isRead == true {
                items[duplicateIndex].isRead = true
                persist(items)
                postDidChange(dsn: normalizedDSN, unreadCount: resolvedBadgeCount(in: items))
            }
            return
        }

        // A chat push's BODY is the parent's message to their child, and this store persists up to
        // 200 items in the app container -- a rolling log of family conversation on the child's
        // device, kept for a badge count that never reads it. Nothing in the app renders any of
        // this. The body is dropped for chat; app-authored notifications (device control, integrity)
        // keep theirs, because that text is generated by this app and is what their tests observe.
        // The fingerprint is computed from the real values first, and is now a digest, so dedupe is
        // unaffected and the retained key is not readable either.
        let item = PushInboxItem(
            id: UUID().uuidString,
            title: normalizedTitle,
            body: Self.carriesPrivateContent(event: normalizedEvent, remoteOrigin: remoteOrigin) ? "" : normalizedBody,
            event: normalizedEvent,
            dsn: normalizedDSN,
            receivedAt: receivedAt,
            isRead: isRead,
            fingerprint: fingerprint
        )

        items.insert(item, at: 0)
        if items.count > maxItems {
            items = Array(items.prefix(maxItems))
        }

        persist(items)
        postDidChange(dsn: normalizedDSN, unreadCount: resolvedBadgeCount(in: items))
    }

    func markAllRead(dsn: String?) {
        let normalizedDSN = dsn?.trimmedNonEmpty?.lowercased()
        var items = storedItems()
        var hasChanges = false

        for index in items.indices {
            let matchesDSN: Bool
            if let normalizedDSN {
                if let itemDSN = items[index].dsn?.lowercased() {
                    matchesDSN = itemDSN == normalizedDSN
                } else {
                    matchesDSN = true
                }
            } else {
                matchesDSN = true
            }

            if matchesDSN, !items[index].isRead {
                items[index].isRead = true
                hasChanges = true
            }
        }

        guard hasChanges else { return }
        persist(items)
        postDidChange(dsn: dsn, unreadCount: resolvedBadgeCount(in: items))
    }

    func markRead(itemID: String, dsn: String?) {
        guard !itemID.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }

        let normalizedDSN = dsn?.trimmedNonEmpty?.lowercased()
        var items = storedItems()
        var hasChanges = false

        for index in items.indices {
            guard items[index].id == itemID else { continue }

            if let normalizedDSN,
               let itemDSN = items[index].dsn?.lowercased(),
               itemDSN != normalizedDSN {
                // Keep DSN-less notifications eligible for current active session.
                continue
            }

            if !items[index].isRead {
                items[index].isRead = true
                hasChanges = true
            }
            break
        }

        guard hasChanges else { return }
        persist(items)
        postDidChange(dsn: dsn, unreadCount: resolvedBadgeCount(in: items))
    }

    func clear(dsn: String?) {
        let normalizedDSN = dsn?.trimmedNonEmpty?.lowercased()
        guard let normalizedDSN else {
            clearAll()
            return
        }

        let existing = storedItems()
        let filtered = existing.filter { item in
            guard let itemDSN = item.dsn?.lowercased() else {
                // Clear ambiguous global notifications on DSN/account switch.
                return false
            }
            return itemDSN != normalizedDSN
        }

        guard filtered.count != existing.count else { return }
        persist(filtered)
        postDidChange(dsn: dsn, unreadCount: resolvedBadgeCount(in: filtered))
    }

    func clearAll() {
        guard !storedItems().isEmpty else {
            updateDiagnostics(items: [], dsn: activeSessionDSN(), status: "inbox_cleared")
            Task { @MainActor in
                UIApplication.shared.applicationIconBadgeNumber = 0
            }
            return
        }

        userDefaults.removeObject(forKey: storageKey)
        updateDiagnostics(items: [], dsn: activeSessionDSN(), status: "inbox_cleared")
        postDidChange(dsn: nil, unreadCount: 0)
    }
}
